photo:
  undirected: False
  self_loops: False
  transpose: False
  dropout: 0.5
  learn_alpha: False
  weight_decay: 0 
  num_epochs: 10000
  hops: 2

  lr: 0.01
  hidden_dim: 64
  num_layers: 2
  jk: "max"
  patience: 600
  conv_type: "dir-gcn"
  alpha: 1
  normalize: True
